on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    name: using tag. Specified Repository path. under root dir
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: Daisugi01/hello-world-composite-action@v0.9
        with:
          who-to-greet: "Mona the Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  hello_world_job2:
    runs-on: ubuntu-18.04
    name: action.yaml under system-test. Specified Repository path.
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: Daisugi01/hello-world-composite-action/.github/actions/system-test@v0.5
        with:
          who-to-greet: "Mona the Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  # hello_world_job3:
  #   runs-on: ubuntu-18.04
  #   name: action.yaml under system-test without version. Specified Repository path
  #   steps:
  #     - uses: actions/checkout@v2
  #     - id: foo
  #       uses: Daisugi01/hello-world-composite-action/.github/actions/system-test
  #       with:
  #         who-to-greet: "Mona the Octocat"
  #     - run: echo random-number ${{ steps.foo.outputs.random-number }}
  #       shell: bash

  hello_world_job4:
    runs-on: ubuntu-18.04
    name: action.yaml under system-test without version. Specified absolute path
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./.github/actions/system-test
        with:
          who-to-greet: "Mona the Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
