on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: Daisugi01/hello-world-composite-action@v4
        with:
          who-to-greet: "Mona the Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: ls -la Daisugi01/hello-world-composite-action@v0.2
        shell: bash

  hello_world_job2:
    runs-on: ubuntu-18.04
    name: A job to say hello2
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: Daisugi01/hello-world-composite-action/.github/system-test.yaml@v0.2
        with:
          who-to-greet: "Mona the Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
