on:
  workflow_call:
    name: "Hello World"
    description: "Greet someone"
    inputs:
      who-to-greet: # id of input
        type: string
        description: "Who to greet"
        required: true
        default: "World"
jobs:
  testing:
    runs-on: ubuntu-18.04
    steps:
      - run: echo Hello ${{ inputs.who-to-greet }}.
        shell: bash
      - id: random-number-generator
        run: echo "::set-output name=random-id::$(echo $RANDOM)"
        shell: bash
      - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
        shell: bash
      - run: ./goodbye.sh
        shell: bash
